#!/bin/bash
# vim: filetype=sh sw=4 ts=4 expandtab

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

#ALACRITTY_HOME=~/.alacritty
#if [ ! -d "${ALACRITTY_HOME}" ]; then
    #export GIT_SSL_NO_VERIFY=true
    #echo '--Downloading alacritty'
    #mkdir -p ~/.alacritty
    #git clone https://github.com/jwilm/alacritty.git ~/.alacritty
    #curl https://sh.rustup.rs -sSf | sh
    #source $HOME/.cargo/env
    #pushd ~/.alacritty
    #make app
    #popd
#else
    #echo "--$ALACRITTY_HOME already exists, please remove for proper installation"
#fi

# alacritty.yml
echo '--Linking alacritty.yml'
mv -v ~/.alacritty.yml ~/.alacritty.yml.old 2> /dev/null
ln -sf $BASE/alacritty.yml ~/.alacritty.yml

