#!/bin/bash
# vim: tabstop=8 softtabstop=4 shiftwidth=4 noexpandtab

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1
BASE=$(pwd)

# My RCs
# for manually linking all RCs:
# what is this?  does this actually work?
: '
for rc in tmux.conf gitconfig bash_profile bashrc zshrc alacritty.yml vimrc; do
  mkdir -pv backup
  [ -e ~/."$rc" ] && mv -v ~/."$rc" backup/."$rc"
  ln -sfv "$(pwd)/$rc" ~/."$rc"
done
'

# Alacritty and vim are in their respective install scripts
for rc in tmux.conf gitconfig bash_profile bashrc zshrc; do
  mkdir -pv backup
  [ -e ~/."$rc" ] && mv -v ~/."$rc" backup/."$rc"
  ln -sfv "$BASE/$rc" ~/."$rc"
done



# My scripts
mkdir -p ~/bin
for bin in $BASE/bin/; do
  ln -svf "$bin" ~/bin
done

# Homebrew
if [ "$(uname -s)" = 'Darwin' ]; then
  # Homebrew
  [ -z "$(which brew)" ] &&
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  echo "--Homebrewing"
  brew cask install sequel-pro alacritty slack dropbox spectacle docker dash

  brew install \
    shellcheck s3cmd docker-compose docker fd ripgrep tmux tmux-xpanes\
    node git tree vim wget jq python python3 go htop nvm \
    zsh zplug \
    #reattach-to-user-namespace \ # This is not required after tmux 2.6!  Needed to remap things before
    cmake # for YCM
fi


# Global Git Config
git config --global user.email "jayjhan8@gmail.com"
git config --global user.name "Jay"

# Install oh-my-zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    echo "--Installing oh-my-zsh since I dun see it"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

# Install powerline
git clone https://github.com/powerline/fonts.git --depth=1
cd fonts || exit
./install.sh
cd .. || exit
rm -rf fonts

# setup NVM
mkdir "$HOME/.nvm"
source $(brew --prefix nvm)/nvm.sh

tmux source-file ~/.tmux.conf
./install-alacritty
./install-vim
